defaults:
  - model_global_variables
  - blocks_zoo_small
  - blocks_zoo_input
  - blocks_zoo
  - encoder: vanilla
  - optimizer: adam
  - scheduler: polynomial_lr
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default
  - override hydra/launcher: basic
  - _self_

hydra:
  job:
    chdir: False
  searchpath:
    - /home/tamara/atomsurf/atomsurf/tasks/shared_conf

# general params
seed: 2024
run_name: cpu_test
data_dir: /home/tamara/data/masif_site
out_dir: /home/tamara/data/masif_site
log_dir: "./"
test_freq: 5
epochs: 2  # reduced for testing
accelerator: "cpu"  # explicitly set CPU
strategy: null  # disable DDP
min_batch_size: 2
use_wandb: False

# loader params
loader:
  num_workers: 0  # reduced for CPU testing
  batch_size: 4  # reduced for CPU testing
  pin_memory: False
  prefetch_factor: 2
  shuffle: true

train:
  save_top_k: 1
  early_stoping_patience: 100
  accumulate_grad_batches: 1
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  limit_train_batches: 0.01  # only use 1% of training data for testing
  limit_val_batches: 0.05    # use 5% of validation data to ensure at least 1 batch
  limit_test_batches: 0.05   # use 5% of test data
  gradient_clip_val: 1.0
  deterministic: False
  max_steps: -1
  auto_lr_find: False
  log_every_n_steps: 10
  detect_anomaly: True  # enabled for testing
  overfit_batches: 0
  to_monitor: auroc/val

cfg_surface:
  use_surfaces: true
  data_dir: ${data_dir}
  data_name: surfaces_0.1_False
  feat_keys: 'all'
  oh_keys: 'all'
  gdf_expand: true

cfg_graph:
  use_graphs: true
  data_dir: ${data_dir}
  data_name: rgraph
  feat_keys: 'all'
  oh_keys: 'all'
  esm_dir: ../../../data/masif_site/esm
  use_esm: false

cfg_head:
  encoded_dims: ${model_hdim}
  output_dims: 1 