defaults:
  - model_global_variables
  - blocks_zoo_small
  - blocks_zoo_input
  - blocks_zoo
  - encoder: pronet_gvpencoder
  - optimizer: adam
  - scheduler: polynomial_lr
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default
  - override hydra/launcher: basic
  - _self_

hydra:
  job:
    chdir: False
  searchpath:
#    - /home/tamara/atomsurf/atomsurf/tasks/shared_conf
    - /root/atomsurf/atomsurf/tasks/shared_conf

# general params
seed: 2024
run_name: default
comment: ""  # Add your experiment comment here
#data_dir: /home/tamara/data/masif_site
#out_dir: /home/tamara/data/masif_site  # does not work for me with chdir=False
data_dir: /root/atomsurf/masif_site_data
out_dir: /root/atomsurf/masif_site_data  # does not work for me with chdir=False
log_dir: "./"
test_freq: 5
epochs: 50
devices: [0]
strategy: "ddp"
path_model: "version_x/checkpoints/last.ckpt"
min_batch_size: 1
use_wandb: False
verbose: true

# loader params
loader:
  num_workers: 16
  batch_size: 64
  pin_memory: True
  prefetch_factor: 4
  shuffle: true

train:
  save_top_k: 2
  early_stoping_patience: 100
  accumulate_grad_batches: 1
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  # gradient clipping
  gradient_clip_val: 1.0
  deterministic: False
  # # epochs and batch_size
  max_steps: -1
  auto_lr_find: False
  log_every_n_steps: 1
  # # detect NaNs
  detect_anomaly: True
  # # debugging
  overfit_batches: 0
  to_monitor: auroc/val

cfg_surface:
  use_surfaces: true
  #  data_dir: ../../../data/masif_site/surfaces
  data_dir: ${data_dir}
  data_name: surfaces_0.1_False
  feat_keys: 'all'
  oh_keys: 'all'
  gdf_expand: true

# python train.py 'cfg_graph.feat_keys=[hphobs]' 'cfg_graph.oh_keys=[amino_types]' cfg_graph.use_esm=True
cfg_graph:
  use_graphs: true
  data_dir: ${data_dir}
  data_name: rgraph
  feat_keys: 'all'
  oh_keys: 'all'
  esm_dir: ../../../data/masif_site/esm
  use_esm: false


cfg_head:
  encoded_dims: ${model_hdim}
  output_dims: 1
